name: Bug Report
description: Report a bug for the MongoDB PHP extension.
title: "Bug: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: >
        You are about to open an issue for the MongoDB PHP extension. If you instead intended to report an issue with
        the MongoDB PHP library, please do so via [its repository](https://github.com/mongodb/mongo-php-library).
        
        If you've identified a security vulnerability in a driver or any other MongoDB project, please
        [create a vulnerability report](https://docs.mongodb.org/manual/tutorial/create-a-vulnerability-report).

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of the driver are you running?
      options:
        - 1.16-dev (development version)
        - 1.15 (stable version)
        - Older version (please specify below)
    validations:
      required: true

  - type: textarea
    id: bug-report
    attributes:
      label: Bug Report
      description: Briefly describe the issue. Explain what happen and what you expected to happen.
    validations:
      required: true

  - type: input
    id: php-version
    attributes:
      label: PHP Version
      description: What version of PHP are you using?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Include other relevant information about your environment. For example:
        * What operating system are you using?
        * What web server are you using?
        * What version of MongoDB are you connecting to?
        * What driver options are you using?
    validations:
      required: true

  - type: textarea
    id: test-script
    attributes:
      label: Test Script
      description: >
        If possible, attach a complete PHP script that can be executed on its own to reproduce the issue. Clarify
        whether this script can be run from the CLI or if it can must be run through a web SAPI.

        If the error only presents itself in a web SAPI, note whether the issue can be reproduced with
        [PHP's built-in web server](http://php.net/manual/en/features.commandline.webserver.php). If not, please share your web server version and any relevant configuration details in the Environment section above.
      render: PHP

  - type: textarea
    id: debug-logs
    attributes:
      label: Debug Logs
      description: >
        If the issue relates to internal driver behavior (e.g. connection issues), please include a
        [debug log](https://www.php.net/manual/en/mongodb.configuration.php#ini.mongodb.debug). This may be generated by
        setting the `mongodb.debug` INI option to "stderr" or a directory (useful for web SAPIs).
      render: Shell
