if test "$PHP_CLIENT_SIDE_ENCRYPTION" != "no"; then
  MONGOCRYPT_CURRENT_FILE=[]PHP_EXT_SRCDIR(mongodb)[/src/LIBMONGOCRYPT_VERSION_CURRENT]
  BUILD_VERSION=$(cat $MONGOCRYPT_CURRENT_FILE)

  AC_SUBST(BUILD_VERSION)
fi
